language: python
python:
- '2.7'

env:
  global:
    - BS_PIP_ALLOWED=1
    - BS_ECHO_DEBUG=1
    - SALT_ARGS="-l debug --local --retcode-passthrough --pillar-root=.salt/pillar --file-root=$PWD"
  matrix:
    - STATE=vhosting

before_install:
  - sudo apt-get update
  - curl -L http://bootstrap.saltstack.org | sudo -E sh -s -- stable

install:
  - sudo mkdir -p /srv && sudo ln -sfn $PWD /srv/formula
  # Show the loaded pillars since the states are generally depending on this
  - sudo salt-call pillar.items $SALT_ARGS
  # See what kind of travis box you're on to help with making your states
  # compatible with travis
  - sudo salt-call grains.items $SALT_ARGS
  # Additional tasks required since this relies on more formulas
  - sudo git clone https://github.com/enrise/nginx-formula.git $PWD/nginx-formula && ln -sfn $PWD/nginx-formula/nginx $PWD/nginx
  - sudo git clone https://github.com/enrise/phpfpm-formula.git $PWD/phpfpm-formula && ln -sfn $PWD/phpfpm-formula/phpfpm $PWD/phpfpm
  - sudo git clone https://github.com/enrise/mariadb-formula.git $PWD/mariadb-formula && ln -sfn $PWD/mariadb-formula/mariadb $PWD/mariadb
  #- sudo git clone https://github.com/enrise/apache-formula.git $PWD/apache-formula && ln -sfn $PWD/apache-formula/nginx $PWD/apache
  #- sudo git clone https://github.com/enrise/zendserver-formula.git $PWD/zendserver-formula && ln -sfn $PWD/zendserver-formula/nginx $PWD/zendserver
  - ls -alh $PWD

script:
  - sudo -E salt-call state.show_sls $STATE $SALT_ARGS
  - sudo -E salt-call state.sls $STATE $SALT_ARGS

  # Idempotence check
  - sudo -E salt-call state.sls $STATE $SALT_ARGS > /tmp/second
  - cat /tmp/second
  - bash -c '! grep -q "^Not Run:" /tmp/second'
